// Configuração do build do projeto
buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.13.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.0"
    }
}

// Configuração comum para todos os módulos
allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

// Tarefa de limpeza
task clean(type: Delete) {
    delete rootProject.buildDir
}